[package]
name = "json2qrcode"
version = "0.1.0"
edition = "2021"

[dependencies]
ab_glyph = "0.2.26"
base64 = "0.22.1"
chrono = "0.4.38"
image = "0.25.1"
imageproc = "0.25.0"
qrcode = "0.14.0"
serde_json = "1.0.117"
